grafana:
  service:
    type: LoadBalancer

  adminPassword: admin

  dashboards:
    default:
      kubernetes:
        gnetId: 315
        datasource: Prometheus

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false

alertmanager:
  enabled: false
