name: Sync ArgoCD Apps

on:
  push:
    branches: [master]
    paths:
      - 'k8s/**'
      - '.github/workflows/sync-argocd-apps.yaml'

jobs:
  sync:
    name: ArgoCD App Sync
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install ArgoCD CLI
        run: |
          curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          chmod +x /usr/local/bin/argocd
          argocd version

      - name: Login to ArgoCD
        run: |
          argocd login ${{ secrets.ARGOCD_SERVER }} \
            --username ${{ secrets.ARGOCD_USERNAME }} \
            --password ${{ secrets.ARGOCD_PASSWORD }} \
            --insecure

      - name: Sync all apps
        run: |
          apps=$(argocd app list -o name)
          for app in $apps; do
            echo "🔄 Syncing $app..."
            argocd app sync $app
          done
